### ISSUE TITLE
Documentation missing examples, showing how to use library

### ISSUE THREAD

**Issue by fidian** [johnpduane/confluence-api#10]
I've got a site that needs to be imported into Confluence. People will view it in Confluence but it is not the authoritative source and so it needs to be imported often so Confluence gets the latest changes. I was looking at your library and at [confluency](https://github.com/heycalmdown/node-confluence). That other library has some useful functions, especially around dealing with children and retrieving all pages within a site. I would potentially use both during the import of this site to Confluence.

I want to also try out yours but the documentation is missing examples. In particular, I was hoping that `.getCustomContentById()` would be powerful enough to get a list of children and maybe I could update pages with `.putContent()`. It is difficult for me to divine how to use these methods when the totality of their documentation is a brief sentence and an explanation of parameter types.

Would you be willing to show examples in your readme? Also, is this library able to get all of the pages in a single space and get all of the children for a single page? Right now it appears that I will be using two Confluence libraries in order to scan for all pages (confluency), upload new pages by title (confluence-api), change page parents (both) and delete pages (both).

**Comment by johnpduane** [comment]
Hi Tyler - Sorry the documentation is missing what you need. The docs in the README are generated by [jsdoc](http://usejsdoc.org/) so are limited to the comments we have in [confluence.js](https://github.com/johnpduane/confluence-api/blob/master/lib/confluence.js). The best examples are in the project's [api-tests.js](https://github.com/johnpduane/confluence-api/blob/master/test/api-test.js) where you can see each of the functions being exercised at least once. Not sure if that is enough for you but it's all we have now.

Here are a two thoughts on getting a full list of pages:
1. This project does not have a wrapper for [Get content](https://docs.atlassian.com/atlassian-confluence/REST/latest/#content-getContent). It can be certainly be added but it's not there today. If you want to submit a pull request with that feature, I would be happy to look at it; otherwise, I can consider adding it myself if this will be a big win for you.
2. If you have less than 25 pages total in the site you are working with, you may be able to get around point 1 above by using the wrapper for [Get content by id](https://docs.atlassian.com/atlassian-confluence/REST/latest/#content-getContentById) and simply providing an empty string in place of the id like so:
```javascript
confluence.getContentById('', function(err, data) {
  // data.results contains an array of pages with a limit of 25
});
```
This call will be limited to 25 pages and does not support the `start` and `limit` parameters you would expect from point 1 above so it's a pretty limited work around!
Hope this helps.

**Comment by fidian** [comment]
Thanks for your reply.

I am aware of jsdoc and I do know you can embed examples, along with paragraphs of documentation and links to further information both within your project and external URLs.  Are you willing to consider extending your jsdoc to include code samples and additional information so the readme will be improved?

**Comment by johnpduane** [comment]
I'd rather not spend time on additional documentation unless there is more demand for it. If other people would like to see this, please give @fidian's request a thumbs up. If there is demand for it, I will make time to do it and I would, of course, be happy to look at a PR if anyone wants to contribute.

Thanks.

**Comment by BeauBouchard** [comment]
I would very much enjoy the documentation. It makes the entrance barrier of using this over competing packages much lower. For my own example for someone not already familiar with what the `space` is for GET or POST content the current readme can be confusing. 

I would be happy to help with some documentation if that is something you are open to.

**Comment by johnpduane** [comment]
I do not plan on adding any additional documentation beyond the jsdoc comments in the code and in the README.md.

If anyone wants to contribute additional documentation, feel free to submit a PR. Thanks!
