### ISSUE TITLE
calls returning null?

### ISSUE THREAD

**Issue by KenHollandWHY** [johnpduane/confluence-api#12]
ar Confluence = require("confluence-api");
var config = {
    username:  "<my name>"
    password: "<my pass>",
    baseUrl:  "https://<my site>.atlassian.net",
    //version: 4 // Confluence major version, optional
};
var confluence = new Confluence(config);
confluence.getSpace("<space name>", function(err, data) {
    // do something interesting with data; for instance,
    // data.results[0].body.storage.value contains the stored markup for the first
    // page found in space 'space-name' matching page title 'page-title'
    console.log(data)
    console.log(err)
    
});

when I run this the output is a {} and a null. 
I know that there is a space and that it has information inside it. 
This is connecting to a confluence cloud instance.

**Comment by johnpduane** [comment]
Hi @KenHollandWHY - I just ran the unit tests for the project, to check if everything is still healthy, and they are passing. In a quick look at your example, here are some thoughts:

The username and password need to be valid.
The baseUrl needs to have a valid subdomain.
The getSpace call needs to have a valid space name.
I assume you removed the above from the example since that data may be sensitive but check them to be sure they are valid.

If all the above checks out then the next thing I would look at is the content in the space. If you do not have any pages there yet, create a few and they should begin populating the `data` variable with content.

If none of that checks out, then we will need to troubleshoot more. Hope this helps.

**Comment by KenHollandWHY** [comment]
Hi @johnpduane 
Thanks for the quick response. Yep, I checked that the username, password and base url are valid and the space has information. 

I know that I am 'touching' confluence because when I made a mistake in typing in my password confluence returned a 401 error. 

I've also been able to access the confluence instance using curl and get a response. I am almost sure I am screwing up somewhere silly but not quite sure where it could be. 


edit: 
fixed it. I made the mistake of calling the name space by its name instead of its key, I realized it once I started curling the different APIs. 

Thanks
