### ISSUE TITLE
Add ancestors to put request

### ISSUE THREAD

**Issue by christopherRiddersater** [johnpduane/confluence-api#8]
First of all, thanks for a nice module. :)

It would be great to be able to use ancestors in the put request to put the page at the desired location/path in the same request. (E.g. the same place it was before the put.)

I will be happy to send a pull request but I would like to have your thoughts on how to implement it.
If you think it's worth implementing at all, that is.
Perhaps a new function could be implemented with options like the getCustomContentById?

**Comment by johnpduane** [comment]
Hi Christopher - Sorry for the long delay responding. I am happy to look at a pull request if you still have interest in adding this feature. I don't have a lot of advice for you on the implementation other than these two things:

1. I'd like to adhere to the open/close principle as much as possible so let's create new functions for these features rather than modifying anything published.
2. Let's create unit tests for anything we add.

If you send a PR, I promise to look at it within a week of getting it. :-)

**Comment by johnpduane** [comment]
Closing this issue; if there is interest in exploring this further in the future, please re-open. Thanks!
